drop rosetta installation

diff --git a/scripts/mac-setup b/scripts/mac-setup
--- a/scripts/mac-setup
+++ b/scripts/mac-setup
@@ -49,12 +49,12 @@ system_install() {
     log "Xcode Command Line Tools already installed. Skipping."
   fi
 
-  if [ "$(uname -m)" = "arm64" ] && ! pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto >/dev/null 2>&1; then
-    log "Installing Rosetta Update. It's okay if this fails."
-    /usr/sbin/softwareupdate --install-rosetta --agree-to-license || true
-  else
-    log "Rosetta Update already installed. Skipping."
-  fi
+  # if [ "$(uname -m)" = "arm64" ] && ! pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto >/dev/null 2>&1; then
+  #   log "Installing Rosetta Update. It's okay if this fails."
+  #   /usr/sbin/softwareupdate --install-rosetta --agree-to-license || true
+  # else
+  #   log "Rosetta Update already installed. Skipping."
+  # fi
 }
 
 brew_install() {
